apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  creationTimestamp: null
  name: iris
  namespace: seldon
spec:
  default:
    predictor:
      logger:
        mode: all
      xgboost:
        nthread: 1
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
        runtimeVersion: v0.3.0
        storageUri: gs://kfserving-samples/models/xgboost/iris
status: {}
